# Test workflow for PyPI publishing
name: Test Release
on:
  workflow_dispatch:  # Manually trigger for testing

jobs:
  test-python-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade build twine

      - name: Update version for testing
        run: |
          sed -i 's/version = ".*"/version = "0.0.1-test"/' pyproject.toml

      - name: Build package
        run: python -m build

      - name: Publish package to TestPyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: python -m twine upload --repository testpypi dist/*